name: "Dependency"
author: "DigitalEngineering"
description: "NuGet Dependencies are able to be used"

inputs:
	name: 
		description: "Name to greet"
		required: false
		default: "Adrian"

runs:
  using: 'node16'
  main: 'src/index.ts'