@startuml
digraph foo {
  "@actions/http-client undefined" -> "@actions/core undefined"
  "uuid undefined" -> "@actions/core undefined"
  "@actions/io undefined" -> "@actions/exec undefined"
  "@actions/http-client undefined" -> "@actions/github undefined"
  "@octokit/core undefined" -> "@actions/github undefined"
  "@octokit/plugin-paginate-rest undefined" -> "@actions/github undefined"
  "@octokit/plugin-rest-endpoint-methods undefined" -> "@actions/github undefined"
  "tunnel undefined" -> "@actions/http-client undefined"
  "@octokit/types undefined" -> "@octokit/auth-token undefined"
  "@octokit/auth-token undefined" -> "@octokit/core undefined"
  "@octokit/graphql undefined" -> "@octokit/core undefined"
  "@octokit/request undefined" -> "@octokit/core undefined"
  "@octokit/request-error undefined" -> "@octokit/core undefined"
  "@octokit/types undefined" -> "@octokit/core undefined"
  "before-after-hook undefined" -> "@octokit/core undefined"
  "universal-user-agent undefined" -> "@octokit/core undefined"
  "@octokit/types undefined" -> "@octokit/endpoint undefined"
  "is-plain-object undefined" -> "@octokit/endpoint undefined"
  "universal-user-agent undefined" -> "@octokit/endpoint undefined"
  "@octokit/request undefined" -> "@octokit/graphql undefined"
  "@octokit/types undefined" -> "@octokit/graphql undefined"
  "universal-user-agent undefined" -> "@octokit/graphql undefined"
  "@octokit/types undefined" -> "@octokit/plugin-paginate-rest undefined"
  "@octokit/types undefined" -> "@octokit/plugin-rest-endpoint-methods undefined"
  "deprecation undefined" -> "@octokit/plugin-rest-endpoint-methods undefined"
  "@octokit/endpoint undefined" -> "@octokit/request undefined"
  "@octokit/request-error undefined" -> "@octokit/request undefined"
  "@octokit/types undefined" -> "@octokit/request undefined"
  "is-plain-object undefined" -> "@octokit/request undefined"
  "node-fetch undefined" -> "@octokit/request undefined"
  "universal-user-agent undefined" -> "@octokit/request undefined"
  "@octokit/types undefined" -> "@octokit/request-error undefined"
  "deprecation undefined" -> "@octokit/request-error undefined"
  "once undefined" -> "@octokit/request-error undefined"
  "@octokit/openapi-types undefined" -> "@octokit/types undefined"
  "whatwg-url undefined" -> "node-fetch undefined"
  "wrappy undefined" -> "once undefined"
  "tr46 undefined" -> "whatwg-url undefined"
  "webidl-conversions undefined" -> "whatwg-url undefined"
  }
  @enduml