@startuml
digraph foo {
  "@actions/core 1.10.0" -> "@actions/http-client ^2.0.1"
  "@actions/core 1.10.0" -> "uuid ^8.3.2"
  "@actions/exec 1.1.1" -> "@actions/io ^1.0.1"
  "@actions/github 5.1.1" -> "@actions/http-client ^2.0.1"
  "@actions/github 5.1.1" -> "@octokit/core ^3.6.0"
  "@actions/github 5.1.1" -> "@octokit/plugin-paginate-rest ^2.17.0"
"@actions/github 5.1.1" -> "@octokit/plugin-rest-endpoint-methods ^5.13.0"
  "@actions/http-client 2.0.1" -> "tunnel ^0.0.6"
  "@octokit/auth-token 2.5.0" -> "@octokit/types ^6.0.3"
  "@octokit/core 3.6.0" -> "@octokit/auth-token ^2.4.4"
  "@octokit/core 3.6.0"  -> "@octokit/graphql ^4.5.8"
  "@octokit/core 3.6.0"  -> "@octokit/request ^5.6.3"
  "@octokit/core 3.6.0"  -> "@octokit/request-error ^2.0.5"
  "@octokit/core 3.6.0"  -> "@octokit/types ^6.0.3"
  "@octokit/core 3.6.0"  -> "before-after-hook ^2.2.0"
  "@octokit/core 3.6.0"  -> "universal-user-agent ^6.0.0"
  "@octokit/endpoint 6.0.12" -> "@octokit/types ^6.0.3"
  "@octokit/endpoint 6.0.12" -> "is-plain-object ^5.0.0"
  "@octokit/endpoint 6.0.12" -> "universal-user-agent ^6.0.0"
  "@octokit/graphql 4.8.0" -> "@octokit/request ^5.6.0"
  "@octokit/graphql 4.8.0" -> "@octokit/types ^6.0.3"
  "@octokit/graphql 4.8.0" -> "universal-user-agent ^6.0.0"
  "@octokit/plugin-paginate-rest 2.21.3" -> "@octokit/types ^6.40.0"
  "@octokit/plugin-rest-endpoint-methods 5.16.2" -> "@octokit/types ^6.39.0"
  "@octokit/plugin-rest-endpoint-methods 5.16.2" -> "deprecation ^2.3.1"
  "@octokit/request 5.6.3" -> "@octokit/endpoint ^6.0.1"
  "@octokit/request 5.6.3" -> "@octokit/request-error ^2.1.0"
  "@octokit/request 5.6.3" -> "@octokit/types ^6.16.1"
  "@octokit/request 5.6.3" -> "is-plain-object ^5.0.0"
  "@octokit/request 5.6.3" -> "node-fetch ^2.6.7"
  "@octokit/request 5.6.3" -> "universal-user-agent ^6.0.0"
  "@octokit/request-error 2.1.0" -> "@octokit/types ^6.0.3"
  "@octokit/request-error 2.1.0" -> "deprecation ^2.0.0"
  "@octokit/request-error 2.1.0" -> "once ^1.4.0"
  "@octokit/types 6.41.0" -> "@octokit/openapi-types ^12.11.0"
  "node-fetch 2.6.7" -> "whatwg-url ^5.0.0"
  "once 1.4.0" -> "wrappy 1"
  "whatwg-url 5.0.0" -> "tr46 ~0.0.3"
  "whatwg-url 5.0.0" -> "webidl-conversions ^3.0.0"

  }
  @enduml