 @startuml
digraph foo {
  "@actions/http-client ^2.0.1" -> "undefined undefined"
  "uuid ^8.3.2" -> "undefined undefined"
  "@actions/io ^1.0.1" -> "undefined undefined"
  "@actions/http-client ^2.0.1" -> "undefined undefined"
  "@octokit/core ^3.6.0" -> "undefined undefined"
  "@octokit/plugin-paginate-rest ^2.17.0" -> "undefined undefined"
  "@octokit/plugin-rest-endpoint-methods ^5.13.0" -> "undefined undefined"
  "tunnel ^0.0.6" -> "undefined undefined"
  "@octokit/types ^6.0.3" -> "undefined undefined"
  "@octokit/auth-token ^2.4.4" -> "undefined undefined"
  "@octokit/graphql ^4.5.8" -> "undefined undefined"
  "@octokit/request ^5.6.3" -> "undefined undefined"
  "@octokit/request-error ^2.0.5" -> "undefined undefined"
  "@octokit/types ^6.0.3" -> "undefined undefined"
  "before-after-hook ^2.2.0" -> "undefined undefined"
  "universal-user-agent ^6.0.0" -> "undefined undefined"
  "@octokit/types ^6.0.3" -> "undefined undefined"
  "is-plain-object ^5.0.0" -> "undefined undefined"
  "universal-user-agent ^6.0.0" -> "undefined undefined"
  "@octokit/request ^5.6.0" -> "undefined undefined"
  "@octokit/types ^6.0.3" -> "undefined undefined"
  "universal-user-agent ^6.0.0" -> "undefined undefined"
  "@octokit/types ^6.40.0" -> "undefined undefined"
  "@octokit/types ^6.39.0" -> "undefined undefined"
  "deprecation ^2.3.1" -> "undefined undefined"
  "@octokit/endpoint ^6.0.1" -> "undefined undefined"
  "@octokit/request-error ^2.1.0" -> "undefined undefined"
  "@octokit/types ^6.16.1" -> "undefined undefined"
  "is-plain-object ^5.0.0" -> "undefined undefined"
  "node-fetch ^2.6.7" -> "undefined undefined"
  "universal-user-agent ^6.0.0" -> "undefined undefined"
  "@octokit/types ^6.0.3" -> "undefined undefined"
  "deprecation ^2.0.0" -> "undefined undefined"
  "once ^1.4.0" -> "undefined undefined"
  "@octokit/openapi-types ^12.11.0" -> "undefined undefined"
  "whatwg-url ^5.0.0" -> "undefined undefined"
  "wrappy 1" -> "undefined undefined"
  "tr46 ~0.0.3" -> "undefined undefined"
  "webidl-conversions ^3.0.0" -> "undefined undefined"
  }
  @enduml