name: Version Increment

on:
  push:
    branches:
      - main

# if the commit message contains the keyword patch,
# the action will only update the patch version. 
# If the keyword is not found, it will update the minor version as before.

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - run: git config user.name "$GITHUB_ACTOR"
      - name: Determine version increment
        id: determine-version
        run: echo "::set-output name=increment::$(echo ${{ github.event.head_commit.message }} | grep -iqE 'patch' && echo 'patch' || echo 'minor')"
      - name: Bump version
        run: npm version ${{ steps.determine-version.outputs.increment }} -m "v%s"
      - run: VERSION=$(node -p "require('./package.json').version")
      - run: git tag ${VERSION}
      - run: git push "https://$GITHUB_ACTOR:${{ secrets.ACCESS_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" --follow-tags
      - run: git push "https://$GITHUB_ACTOR:${{ secrets.ACCESS_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" --tags
