name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  build:
    name: Run Action
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: [6.0.x]
        

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
      # npm ci == npm install but gives feedback if not up-to-date
        run: npm ci

      - name: Build
        run: npm run build --if-present
    


      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
            

      - name: update packages
        uses: ./
        id: update
        with:
          version-limit: 'minor'
          comment-updated: true
          write-mode: append
          ignore: |         

      # - name: Commit & Push
      #   uses: Andro999b/push@v1.3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: main
      #     force: true
      #     message: 'Overwritten by Github Actions - ${date}'
