name: Test
on:
  push:
    branches:
      - main
    tags-ignore:
      - v*
  pull_request:
    branches:
      - main
  
jobs:
  build:
    name: Run Action
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: [6.0.x]
        

    steps:
      - uses: actions/checkout@v2
      # - run: git config user.name "$GITHUB_ACTOR"
      # - run: npm version patch -m "v%s"
      # - run: VERSION=$(node -p "require('./package.json').version")
      # - run: git tag ${VERSION}
      # - run: git push "https://$GITHUB_ACTOR:${{ secrets.ACCESS_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" --follow-tags
      


      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: package-lock.json


      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: dotnet Restore
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Test
        run: dotnet test --no-restore --verbosity normal


      - name: Install dependencies
      # npm ci == npm install but gives feedback if not up-to-date
        run: npm ci

      - name: Build
        run: npm run build --if-present

      # - name: SemVer
      #   uses: ./
      #   id: semver
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     WITH_V: true  


      - name: update packages
        uses: ./
        id: update
        with:
          packageToUpdate: 'Microsoft.AspNetCore.Razor'
          version-limit: 'minor'
          comment-updated: true
          write-mode: append
          ignore: 'Microsoft.EntityFrameworkCore.SqlServer'

      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: `Overwritten by Github Actions - ${date}`


      

